#define LIST_HEADER "Category,Name,File"

#include "applist.h"
#include <qfile.h>

bool AppList::ReadAppList(QDir path){
	QString line;
	QStringList data;
	QFile file(QDir::toNativeSeparators(path.path()));

	//CSV file opened
	if (!file.open(QIODevice::ReadOnly))
		return false;

	//test if valid columns
	line = file.readLine().simplified();
	if(line.compare(LIST_HEADER) != 0)
		return false;

	//clear previus value from memory
	_categories.clear();
	for(int i=0; i<N_COLS; i++)
		_apps[i].clear();

	//parse file
	for(int i=0; !file.atEnd(); i++){
		//read current line
		line = file.readLine().simplified();
		if (line.compare("") == 0)
			continue;

		//split line into tokens
		data = line.split(",");
		if (data.size() != N_COLS){
			file.close();
			return false;
		}

		//add category to the list if necesary
		if(!_categories.contains(data.at(APP_CATEGORIES)))
			_categories.append(data.at(APP_CATEGORIES));

		_apps[APP_CATEGORIES].append(QString("%1").arg(FindCategoryIndex(data.at(APP_CATEGORIES))));

		//add app to the list
		_apps[APP_NAMES].append(data.at(APP_NAMES));
		_apps[APP_DIRS].append(data.at(APP_DIRS));
	}
	file.close();

	return true;
}

int AppList::FindCategoryIndex(QString category){
	return _categories.indexOf(category);
}

int AppList::CategoriesSize(){
	return _categories.size();
}

QString AppList::GetCategoryName(int index){
	return _categories.at(index);
}

int AppList::AppsAmount(){
	return _apps[0].size();
}

int AppList::GetAppCategoryIndex(int index){
	return _apps[APP_CATEGORIES].at(index).toInt();
}

QString AppList::GetAppValue(int type, int index){
	return _apps[type].at(index);
}

QStringList* AppList::GetCategoriesRef(){
	return &_categories;
}

void AppList::Append(QString category,
			QString name,
			QString dir)
{
	if(!_categories.contains(category))
		_categories.append(category);

	_apps[0].append(QString("%1").arg(_categories.indexOf(category)));
	_apps[1].append(name);
	_apps[2].append(dir);
}

void AppList::RemoveAt(int index){
	_apps[0].removeAt(index);
	_apps[1].removeAt(index);
	_apps[2].removeAt(index);
}

void AppList::Replace(int i,
			 QString category,
			 QString name,
			 QString dir)
{
	if(!_categories.contains(category))
		_categories.append(category);

	_apps[0].replace(i, QString("%1").arg(_categories.indexOf(category)));
	_apps[1].replace(i, name);
	_apps[2].replace(i, dir);
}

bool AppList::CategoryExists(QString category){
	if(_categories.contains(category))
		return true;
	return false;
}

void AppList::Clear(){
	_categories.clear();

	for(int i=0; i<N_COLS; i++){
		_apps[i].clear();
	}
}

void AppList::OnSaveList(){
	int i, j, nApps = AppsAmount();
	QFile file(DEFAULT_LIST_PATH_.path());

	//CSV file opened
	if (!file.open(QIODevice::WriteOnly))
		return;

	file.write(LIST_HEADER);
	file.write("\n");
	for(i=0; i<nApps; i++){
		file.write(_categories.at(_apps[0].at(i).toInt()).toStdString().c_str());
		for(j=1; j< N_COLS; j++){
			file.write(",");
			file.write(_apps[j].at(i).toStdString().c_str());
		}
		file.write("\n");
	}

	file.close();
}

void AppList::AutogenerateDirs(){
	Clear();
	foreach(QFileInfo file, QDir("Apps").entryInfoList(QDir::NoDotAndDotDot|QDir::Files, QDir::Type)){
		Append("", "", file.fileName());
	}
}
